name: news_app
description: "A news app."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.10.0
  curved_navigation_bar: ^1.0.6
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
